### ISSUE TITLE
still relevant?

### ISSUE THREAD

**Issue by prototype99** [CFSworks/nvml_fix#11]
my nvidia-smi `output:`
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.24                 Driver Version: 396.24                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:24:00.0  On |                  N/A |
|  0%   43C    P0    40W / 210W |   1917MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       489      G   /usr/bin/X                                  1025MiB |
|    0       662      G   kwin_x11                                     313MiB |
|    0       668      G   /usr/bin/krunner                               3MiB |
|    0       670      G   /usr/bin/plasmashell                         178MiB |
|    0      3432      G   /usr/bin/firefox                             384MiB |
|    0      3563      G   /usr/lib64/firefox/firefox                     3MiB |
|    0      7775      G   /usr/lib64/firefox/firefox                     3MiB |
|    0      9233      G   /usr/lib64/firefox/firefox                     3MiB |
+-----------------------------------------------------------------------------+
is it really missing anything? that looks like a full output

**Comment by dangpzanco** [comment]
It is, apparently, still relevant:

```
daniel@daniel-avell:~$ nvidia-smi
Tue Oct  9 22:13:13 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.54                 Driver Version: 396.54                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 675MX   Off  | 00000000:01:00.0 N/A |                  N/A |
| N/A   43C    P8    N/A /  N/A |     54MiB /  4037MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
```

**Comment by prototype99** [comment]
ah they changed it to 'though limited support is also available on other NVIDIA GPUs.'
