### ISSUE TITLE
no effect on 418.56

### ISSUE THREAD

**Issue by nithinpachday** [CFSworks/nvml_fix#22]
I have done the above steps but still, I have the same issue. I am using an Nvidia GeForce 920M integrated GPU on Ubuntu 18.04LTS

**Comment by tofurky** [comment]
can you please provide the following? it will probably be necessary to `apt install ltrace` first.
```
ltrace -s1024 -S -o nvidia-smi-ltrace.out nvidia-smi
```
and attach nvidia-smi-ltrace.out to this issue.

**Comment by nithinpachday** [comment]
I have attached the nvidia-smi-trace.out as a zip file.

[nvidia-smi-ltrace.zip](https://github.com/CFSworks/nvml_fix/files/3226610/nvidia-smi-ltrace.zip)

**Comment by tofurky** [comment]
hmm, it looks like it's attempting to query the power usage (via `ioctl()` on `/dev/nvidiactl`) but not getting a result. this means that nvml_fix is doing what it's supposed to, although it might be attempting that without nvml_fix installed as well - the 920m is a newer gpu released in 2015 or so.

i think this might have to do with the "optimus" switching between the cpu's iGPU and the discrete nvidia. if you open up the `nvidia-settings` program, do you see a section like this? is nvidia selected?
![image](https://user-images.githubusercontent.com/4065513/58498897-0356dd00-814d-11e9-82c6-1e60543031ec.png) (taken from https://mintguide.org/system/208-install-nvidia-prime-of-nvidia-optimus-into-linux-mint-17.html)

it might be necessary to logout/reboot after changing that option, if it's set to intel.

also, just curious - can you please run `nvidia-smi -a > nvidia-smi.out` and attach nvidia-smi.out?

**Comment by tofurky** [comment]
i guess github doesn't support attaching files with a .out suffix, you can just rename it to .txt and attach.

**Comment by nithinpachday** [comment]
[nvidia-smi.txt](https://github.com/CFSworks/nvml_fix/files/3231155/nvidia-smi.txt)

as you requested I Have attached the nvidia-smi.out file with .txt extention. I have already enabled NVIDIA in power settings.
![Screenshot from 2019-05-29 12-44-06](https://user-images.githubusercontent.com/46375818/58536959-7fb1f480-820f-11e9-9570-59966e9eb7be.png)

**Comment by tofurky** [comment]
thanks, i was wanting to see the "PRIME Profiles" section, but you said it's already set to `NVIDIA (Performance Mode)`?

**Comment by nithinpachday** [comment]
Sorry for the mistake. Under prime profiles I selected NVIDIA.

**Comment by tofurky** [comment]
can you please also run `strace -s1024 -o nvidia-smi-strace.txt nvidia-smi` and attach that here? i'm thinking though that the card firmware isn't responding to power utilization queries :(

**Comment by nithinpachday** [comment]
[nvidia-smi-strace.txt](https://github.com/CFSworks/nvml_fix/files/3233935/nvidia-smi-strace.txt)
here is the nvidia-strace file.

**Comment by neerajvashistha** [comment]
thank you for breaking the system :)

```
$ nvidia-smi
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.
$ 
```
before
```
$ ls -lrth ./lib/x86_64-linux-gnu/libnvidia-ml.so.1
lrwxrwxrwx 1 root root 25 Nov 13 21:27 ./lib/x86_64-linux-gnu/libnvidia-ml.so.1 -> libnvidia-ml.so.440.33.01
```

after, I followed the steps listed in readme 
```
nv@nv-workstation:~$ cd nvml_fix/
nv@nv-workstation:~/nvml_fix$ make TARGET_VER=440.33
make: Nothing to be done for 'all'.
$ sudo rm /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
$ sudo make install TARGET_VER=440.33 libdir=/usr/lib/x86_64-linux-gnu
$ ls -lrth /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
-rwxr-xr-x 1 root root 10K Feb 19 00:17 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
$ nvidia-smi
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.
```

Fixed it by creating the symbolic link again.
```
$ cd /usr/lib/x86_64-linux-gnu/
$ sudo rm libnvidia-ml.so.1
$ sudo ln -s libnvidia-ml.so.440.33.01 libnvidia-ml.so.1
```

**Comment by tofurky** [comment]
from what you've posted, i think you need `TARGET_VER=440.33.01`, not `TARGET_VER=440.33`

**Comment by neerajvashistha** [comment]
> from what you've posted, i think you need `TARGET_VER=440.33.01`, not `TARGET_VER=440.33`

I tried 440.33.01 too, but same error.

**Comment by tofurky** [comment]
please attach debugging output as described earlier in this issue (with nvml_fix installed). you may need to install one or both of `ltrace` and `strace`:

nvidia-smi-ltrace.txt:
```
ltrace -s1024 -S -o nvidia-smi-ltrace.txt nvidia-smi
```
nvidia-smi-strace.txt:
```
strace -s1024 -o nvidia-smi-strace.txt nvidia-smi
```
nvidia-libs.txt:
```
ls -l /usr/lib*/{*nvidia*,libnv*} /usr/lib/*/{*nvidia*,libnv*} > nvidia-libs.txt
```

also it would be nice to see what the output of nvidia-smi is *without* nvml_fix installed:
nvidia-smi.txt:
```
nvidia-smi -a > nvidia-smi.txt
```
