### ISSUE TITLE
how about 430.14 ? ;)

### ISSUE THREAD

**Issue by smooker** [CFSworks/nvml_fix#23]
/var/tmp/portage/x11-drivers/nvidia-drivers-430.14/work/kernel/nvidia/nv-pat.c
line 145 missing semicolon 

regards,
smooker.

**Comment by tofurky** [comment]
does `TARGET_VER=430.14` not work? also, what does that missing semicolon error have to do with nvml_fix?

**Comment by tofurky** [comment]
fixed in current master.
