### ISSUE TITLE
Doesn't work with GT710 + 440.36 + CUDA 10.2 

### ISSUE THREAD

**Issue by gonzalezcalleja** [CFSworks/nvml_fix#29]
Hi,

I have problems to enable process usage information from nvidia-smi with:
- GT710
- 440.36 driver
- nvml_fix (commit 32c55498abe2cf12ef7e88906285b7714838f46b)

Here is the output:

![image](https://user-images.githubusercontent.com/3635557/71489617-b3491180-2826-11ea-8a08-e964f984dd44.png)

And here attached output debug logs:

[nvidia-smi.txt](https://github.com/CFSworks/nvml_fix/files/4003413/nvidia-smi.txt)
[nvidia-smi-strace.txt](https://github.com/CFSworks/nvml_fix/files/4003414/nvidia-smi-strace.txt)

I also have in nvidia-settings the powermizer settings to "Prefer Maximum Performance".

Thanks for your support!

**Comment by tofurky** [comment]
hi,
thanks for providing the detailed information right off the bat :)
it appears that everything is working as it should be from nvml_fix's end. you can confirm by reverting to stock configuration, and re-running `nvidia-smi -a`.
notice the following from the output you provided:
```
Attached GPUs                       : 1
GPU 00000000:07:00.0
    Product Name                    : GeForce GT 710
    Product Brand                   : Quadro
    Display Mode                    : Enabled
    Display Active                  : Enabled
    Persistence Mode                : Disabled
```
it is being detected as `Quadro`, which means that it's tricking the libnvidia-ml library as it is supposed to.
i think unfortunately that in these cases, for some reason the chipset itself, or the video bios, is not capable of reporting the power utilization/processes :(
if you revert to original config, and see `nvidia-smi -a` again, it will likely show:
```
    Product Brand                   : GeForce
```

**Comment by gonzalezcalleja** [comment]
Hi,

Thanks for your quick answer! 

With "stock nvidia lib" i have notice that i can't see the CPU usage, but with your patch I can see it, so this should be enough.

![Screenshot 2019-12-27 at 15 26 32](https://user-images.githubusercontent.com/3635557/71520628-5fd5d280-28bd-11ea-9c73-346c649a4630.png)

I think that i will bought a bigger GPU because i'm starting to play with tensorflow ... are the any list of compatible GPUs with nvml_fix? Thanks!

**Comment by tofurky** [comment]
sorry, there isn't a list of compatible GPUs. i only have a single nvidia card (650 ti oc boost) which is of course working :)
i suspect that cards that use the same underlying gpu chips that the quadro line uses would probably work.
if you go to https://en.wikipedia.org/wiki/Nvidia_Quadro#Quadro, there is a column named "Near GeForce Model".
no guarantees of course but i would say that is an educated guess.

**Comment by tofurky** [comment]
closing as this appears to be a hardware/firmware limitation rather than something within the scope of things nvml_fix could address.
