### ISSUE TITLE
New driver version 325.15

### ISSUE THREAD

**Issue by arclance** [CFSworks/nvml_fix#3]
The new stable driver 325.15 was released two days ago.
Are any changes needed to use this fix with the new version other than specifying it's version at build time?

**Comment by tofurky** [comment]
closing due to age. if people are still experiencing issues with current driver versions on supported hardware (fermi or newer, see https://stackoverflow.com/questions/19761056/nvml-power-readings-with-nvmldevicegetpowerusage), please open a new issue, thanks.
