### ISSUE TITLE
I had to create a link to libnvidia-ml.so.470.57.02

### ISSUE THREAD

**Issue by CavernDigger88** [CFSworks/nvml_fix#40]
Awesome fix... I have an old NVIDIA GeForce GTX 690 which now works with nvidia-smi
Thank you... But I had to do one extra step.

I did the following :
make TARGET_VER=470.57
make install TARGET_VER=470.57 libdir=/usr/lib/x86_64-linux-gnu

but I after that I had the following files : 
ls -1 /usr/lib/x86_64-linux-gnu/libnvidia-ml*
/usr/lib/x86_64-linux-gnu/libnvidia-ml.so
/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.470.57.02

I had to : 
ln -s /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.470.57.02 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.470.57

Its working . I'm not touching it anymore.

**Comment by tofurky** [comment]
since you're using 470.57.02, you would need to do TARGET_VER=470.57.02
